# -*- coding: utf-8 -*-
# Real per-speaker metadata for Piper's en_US-libritts_r-medium voice -
# gender + the reader's own registered LibriVox name, cross-referenced
# from LibriTTS-R's own real speakers.tsv (OpenSLR resource 141,
# https://www.openslr.org/141/) against this voice's own speaker_id_map
# (in its .onnx.json config) - confirmed a full 904/904 match, no gaps,
# no duplicate names. The key is the string form of Piper's own internal
# speaker_id (0-903, what /synthesize actually expects), sorted by name
# so the picker is alphabetically browsable rather than a bare ID list.
LIBRITTS_R_SPEAKERS = [
    ("326", "Aaron Andradne (Male)"),
    ("795", "Aaron Decker (Male)"),
    ("713", "Aaron Elliott (Male)"),
    ("666", "Aaron Weber (Male)"),
    ("378", "Abigail Rasmussen (Female)"),
    ("464", "Acacia Wood (Female)"),
    ("465", "ACBowgus (Male)"),
    ("609", "acloward (Male)"),
    ("605", "Adam Taylor (Male)"),
    ("608", "Adib Masumian (Male)"),
    ("594", "AdrianBisson (Male)"),
    ("538", "Al Dano (Male)"),
    ("216", "Alan Winterrowd (Male)"),
    ("178", "Alana Jordan (Female)"),
    ("846", "Aldark (Male)"),
    ("589", "Alec Daitsman (Male)"),
    ("191", "Alex C. Telander (Male)"),
    ("633", "Alex Patterson (Male)"),
    ("519", "Alexander Hatton (Male)"),
    ("14", "Alexandra Huckabay (Female)"),
    ("478", "Alexandre Laplante (Male)"),
    ("734", "Alfian (Male)"),
    ("327", "Ali Kazerani (Male)"),
    ("679", "AliceG (Female)"),
    ("728", "Alina (Female)"),
    ("215", "Alisa (Female)"),
    ("75", "Alison Stewart (Female)"),
    ("523", "AllenJohns (Male)"),
    ("645", "alwpoe (Male)"),
    ("54", "Alys AtteWater (Female)"),
    ("9", "Amanda Friday (Female)"),
    ("63", "Amy Benton (Female)"),
    ("309", "Amy Gramour (Female)"),
    ("766", "Amy Koenig (Female)"),
    ("196", "amycs (Female)"),
    ("4", "AmyG (Female)"),
    ("211", "Andrea Boltz (Female)"),
    ("761", "Andrea L (Female)"),
    ("183", "Andrew Hernandez (Male)"),
    ("597", "Andrew Nelson (Male)"),
    ("899", "Andrew Symons (Male)"),
    ("259", "Andrew Vidal (Male)"),
    ("673", "Andrew White (Male)"),
    ("628", "Angela Kelley (Female)"),
    ("255", "Anise (Female)"),
    ("702", "Anna Millard (Female)"),
    ("57", "Anna Roberts (Female)"),
    ("710", "Anna Simon (Female)"),
    ("682", "Anna-Maria Viola (Female)"),
    ("453", "Annie Coleman Rothenberg (Female)"),
    ("347", "Annie Kirkpatrick (Female)"),
    ("901", "anonymous (Male)"),
    ("203", "Anthony Craine (Male)"),
    ("16", "Anthony Wilson (Male)"),
    ("893", "Anton (Male)"),
    ("839", "Antonio (Male)"),
    ("149", "Arlene Joyce (Female)"),
    ("199", "Arouet (Male)"),
    ("300", "Art Leung (Female)"),
    ("0", "Ashley Candland (Female)"),
    ("128", "ASPotter (Female)"),
    ("79", "Astrid Fingerhut (Female)"),
    ("831", "Ata Khudayberdiev (Male)"),
    ("454", "audiotoshokan (Male)"),
    ("185", "ayngelwing (Female)"),
    ("672", "B. G. Oxford (Female)"),
    ("880", "B. Grebe (Female)"),
    ("77", "Barbara Bulkeley (Female)"),
    ("192", "Barbara Clements (Female)"),
    ("517", "Barbara Harvey (Female)"),
    ("407", "BDSEmpire (Male)"),
    ("123", "Bear Schacht (Male)"),
    ("17", "Becca B (Female)"),
    ("537", "Becky Cook (Female)"),
    ("883", "Ben Douglas (Male)"),
    ("220", "Benuathanasia (Female)"),
    ("561", "Beth Dudek (Female)"),
    ("213", "Bethany Simpson (Female)"),
    ("354", "Betty Perry (Female)"),
    ("565", "Bev J Stevens (Female)"),
    ("470", "Beverly Scott (Female)"),
    ("132", "Bigcowfeet (Male)"),
    ("716", "BigStory (Male)"),
    ("78", "Bill Ruhsam (Male)"),
    ("814", "Bill Stackpole (Male)"),
    ("371", "Bill Yallalee (Male)"),
    ("800", "bish (Male)"),
    ("598", "Bob Gonzalez (Male)"),
    ("201", "Bob Graff (Male)"),
    ("758", "Bob Sage (Male)"),
    ("139", "Bob Stretch (Male)"),
    ("607", "Bob Tassinari (Male)"),
    ("253", "bobbybrill (Male)"),
    ("126", "Bookworm (Female)"),
    ("564", "Brad Powers (Male)"),
    ("349", "Brenda Dayne (Female)"),
    ("756", "Brendan Brown (Male)"),
    ("653", "Brendan Stallard (Male)"),
    ("821", "Brett Condron (Male)"),
    ("2", "Brett W. Downey (Male)"),
    ("809", "Brian Keith Barnes (Male)"),
    ("167", "Bridget Gaige (Female)"),
    ("44", "Brooks Jensen (Male)"),
    ("744", "Brooks Seveer (Male)"),
    ("896", "Brother Patrick (Male)"),
    ("886", "browneyedgirl32382 (Female)"),
    ("436", "Bruce Kachuk (Male)"),
    ("842", "Bruce Stafford (Male)"),
    ("256", "Bryan Reid (Male)"),
    ("779", "C. Berrius (Male)"),
    ("864", "C.L.Coney (Female)"),
    ("374", "Caden Vaughn Clegg (Male)"),
    ("85", "Cagirlwithasoutherndrawl (Female)"),
    ("267", "Caitlin Kelly (Female)"),
    ("586", "Carl Manchester (Male)"),
    ("476", "Carl Vonnoh, III (Male)"),
    ("872", "Carol (Female)"),
    ("777", "Carol Goode (Female)"),
    ("440", "Caroline Mercier (Female)"),
    ("757", "Carolyn Frances (Female)"),
    ("324", "Cate Barratt (Female)"),
    ("574", "Catherine Fitz (Female)"),
    ("148", "cbooren (Female)"),
    ("737", "Celena Arter (Female)"),
    ("159", "Charles RUHE (Male)"),
    ("844", "Charlie Blakemore (Male)"),
    ("783", "Chela (Female)"),
    ("242", "cher0520 (Female)"),
    ("411", "Chere Theriot (Female)"),
    ("285", "Cheri Gardner (Female)"),
    ("236", "Cheri Jordan (Female)"),
    ("306", "Chessie Joy (Female)"),
    ("686", "Chris Amos (Male)"),
    ("55", "Chris Caron (Male)"),
    ("361", "Chris Clark (Male)"),
    ("257", "Chris Masterson (Male)"),
    ("684", "Chris Mitchell (Male)"),
    ("804", "Chris Pauley (Male)"),
    ("637", "chris tierney (Male)"),
    ("357", "Chris Vee (Male)"),
    ("742", "ChrisC (Male)"),
    ("856", "Christian Mitchell (Male)"),
    ("328", "Christian Pecaut (Male)"),
    ("550", "Christiane Levesque (Female)"),
    ("614", "Christina M. Glavas (Female)"),
    ("419", "Christine Dufour (Female)"),
    ("161", "Christine Nendza (Female)"),
    ("40", "Christine Rodriguez (Female)"),
    ("445", "Christopher Jennings (Male)"),
    ("114", "Christopher Maust (Male)"),
    ("182", "Christopher Webber (Male)"),
    ("543", "Chuck Spann (Male)"),
    ("599", "Cindy Steib (Female)"),
    ("712", "Clacas (Female)"),
    ("160", "Claire M (Female)"),
    ("250", "Clarica (Female)"),
    ("217", "clarknova (Male)"),
    ("857", "Claude Banta (Male)"),
    ("377", "Claudia Wilson (Female)"),
    ("869", "Claudine Chen (Female)"),
    ("884", "Clayton J. Smith (Male)"),
    ("735", "Cody2 (Male)"),
    ("815", "Collee McKinnon (Female)"),
    ("243", "compozr (Male)"),
    ("542", "Conrad T (Male)"),
    ("23", "Corinna Schultz (Female)"),
    ("812", "Corun (Male)"),
    ("140", "Courtney Sandhu (Female)"),
    ("71", "cpalmer17 (Male)"),
    ("8", "Craig Kenneth Bryant (Male)"),
    ("311", "Cynthia Moyer (Female)"),
    ("656", "Cynthia Zocca (Female)"),
    ("481", "D. T. McGregor (Male)"),
    ("773", "Dale A. Bade (Female)"),
    ("343", "daltongirl (Female)"),
    ("640", "Dan Froese (Male)"),
    ("227", "Dan Mason (Male)"),
    ("861", "Dan Polanco (Male)"),
    ("827", "Dan Threetrees (Male)"),
    ("534", "Danarra (Female)"),
    ("95", "Dani (Female)"),
    ("721", "Daniel T. Miller (Male)"),
    ("654", "Daniel Vimont (Male)"),
    ("708", "Danielle (Female)"),
    ("794", "Danielle Flores (Female)"),
    ("391", "DannyHauger (Male)"),
    ("390", "dave7 (Male)"),
    ("452", "davechase (Male)"),
    ("81", "David A. Moore. (Male)"),
    ("685", "David Baldwin (Male)"),
    ("200", "David Best (Male)"),
    ("802", "David Callahan (Male)"),
    ("751", "David Cummings (Male)"),
    ("479", "David D'Huet (Male)"),
    ("848", "David Jaquay (Male)"),
    ("483", "David Leeson (Male)"),
    ("289", "David O'Connell (Male)"),
    ("540", "David Schoepf (Male)"),
    ("890", "David Shamp (Male)"),
    ("715", "davidb (Male)"),
    ("244", "Dawn (Female)"),
    ("3", "Dayle (Male)"),
    ("277", "Deanna Bovee (Female)"),
    ("98", "Deborah Clark (Female)"),
    ("397", "Dee Wykoff (Male)"),
    ("150", "Deena Rhoads (Female)"),
    ("45", "Denice Stradling (Female)"),
    ("37", "Denise Nordell (Female)"),
    ("745", "Denise Resnik (Female)"),
    ("19", "Dennis Blake (Male)"),
    ("491", "Devon Purtz (Male)"),
    ("50", "dgulino (Male)"),
    ("451", "Diana Dolan (Female)"),
    ("312", "Diana Kiesners (Female)"),
    ("806", "Diapadion (Male)"),
    ("803", "Dillon Stiles (Male)"),
    ("248", "DJRickyV (Male)"),
    ("760", "DL Pead (Male)"),
    ("642", "Doctor_wu (Male)"),
    ("513", "dolce (Female)"),
    ("432", "Don Halpert (Male)"),
    ("387", "Don W. Jenkins (Male)"),
    ("32", "Doug Allison (Male)"),
    ("882", "Doug Delisle (Male)"),
    ("631", "Doug Wetzel (Male)"),
    ("232", "DPranitis (Male)"),
    ("147", "DrBeccaAnne (Female)"),
    ("770", "drewmac (Male)"),
    ("740", "dsilber01 (Male)"),
    ("663", "DublinGothic (Male)"),
    ("431", "durnburr (Male)"),
    ("163", "DVoice (Female)"),
    ("739", "dwegowy (Male)"),
    ("789", "Dylan Posa (Male)"),
    ("69", "E Ogston (Female)"),
    ("555", "E. Plein (Female)"),
    ("91", "e.a.zokaites (Female)"),
    ("536", "Easton (Female)"),
    ("541", "EccentricOwl (Male)"),
    ("293", "echo (Male)"),
    ("499", "Ed Meade (Male)"),
    ("58", "Edward Elmer (Male)"),
    ("527", "Edward W. LaBonte (Male)"),
    ("11", "Eileen aka e (Female)"),
    ("197", "Eileen George (Female)"),
    ("670", "ej (Male)"),
    ("305", "Elena (Female)"),
    ("425", "elfpen (Male)"),
    ("573", "Elin (Male)"),
    ("582", "Elizabeth Klett (Female)"),
    ("113", "Elliott Miller (Male)"),
    ("557", "Elsa Youngsteadt (Female)"),
    ("850", "Emily Anderson (Female)"),
    ("93", "Emily Feuka (Female)"),
    ("366", "Emily Jarmard (Female)"),
    ("202", "Emily Livingston (Female)"),
    ("873", "Emily Maynard (Female)"),
    ("389", "entada (Female)"),
    ("898", "Eric (Male)"),
    ("35", "Eric Leach (Male)"),
    ("86", "Eric Metzler (Male)"),
    ("870", "Eric Ray (Male)"),
    ("747", "Eric S. Piotrowski (Male)"),
    ("796", "Erica Kuntz (Female)"),
    ("408", "Erin Schellhase (Female)"),
    ("502", "Ernst Schnell (Male)"),
    ("412", "Esther (Female)"),
    ("858", "Estragon (Male)"),
    ("368", "Expatriate (Male)"),
    ("694", "EyeBones (Female)"),
    ("344", "FaithR (Female)"),
    ("698", "Fiddlesticks (Female)"),
    ("835", "firefly (Female)"),
    ("330", "Floyd Wilde (Male)"),
    ("701", "Frances Marcinkiewicz (Female)"),
    ("902", "Frank Adams (Male)"),
    ("771", "frenchfry (Female)"),
    ("683", "Furio (Male)"),
    ("448", "Fuzz (Female)"),
    ("334", "gabrielv (Male)"),
    ("649", "Gail Mattern (Female)"),
    ("692", "Gail Timmerman Vaughan (Female)"),
    ("304", "galaxiant (Male)"),
    ("577", "garbageman99 (Male)"),
    ("752", "Gargoyle (Male)"),
    ("135", "Gary Bohannon (Male)"),
    ("286", "Gary Coy (Male)"),
    ("341", "Gary Ericson (Male)"),
    ("720", "Gary Gilberd (Male)"),
    ("442", "Gary W. Sherwin (Male)"),
    ("393", "garymacf (Male)"),
    ("155", "Gayland Darnell (Male)"),
    ("109", "Gen Jones (Female)"),
    ("219", "Geoff Cowgill (Male)"),
    ("504", "Geoffrey Edwards (Male)"),
    ("774", "geofred (Male)"),
    ("570", "George Yeager (Male)"),
    ("473", "gfairch511 (Male)"),
    ("881", "Gigi Minden (Female)"),
    ("717", "Gina (Female)"),
    ("34", "Glenn Simonsen (Male)"),
    ("333", "Gloria Zbilicki (Female)"),
    ("320", "gloriousjob (Male)"),
    ("805", "Gord Mackenzie (Male)"),
    ("264", "Goss45 (Male)"),
    ("477", "Graham McMillan (Male)"),
    ("403", "Greengecko (Female)"),
    ("591", "Greg Bell (Male)"),
    ("854", "Greg Elmensdorp (Male)"),
    ("231", "Greg Giordano (Male)"),
    ("459", "Greg Golding (Male)"),
    ("852", "Greg Hartley (Male)"),
    ("156", "Greg W. (Male)"),
    ("6", "Greg Weeks (Male)"),
    ("435", "Gregg Margarite (1957-2012) (Male)"),
    ("375", "Guero (Male)"),
    ("786", "Gwyneth (Female)"),
    ("620", "haggisreflux (Male)"),
    ("514", "HappyMiamiDad (Male)"),
    ("237", "Hayden (Female)"),
    ("785", "Heather Duncan (Female)"),
    ("15", "Heather Lawrence (Female)"),
    ("25", "Heather Ordover (Female)"),
    ("790", "Heidi Preuss (Female)"),
    ("224", "helengraves (Female)"),
    ("807", "hgal2010 (Female)"),
    ("263", "Highlandoaks (Female)"),
    ("101", "hollz (Female)"),
    ("531", "Hoosemon (Male)"),
    ("834", "HotConflict (Male)"),
    ("810", "hpark (Female)"),
    ("584", "Hugh Gillis (Male)"),
    ("697", "hugh mac (Male)"),
    ("399", "humanode (Male)"),
    ("626", "humeangel (Female)"),
    ("117", "Ian Grae (Male)"),
    ("22", "Ian Quinlan (Male)"),
    ("426", "Icprice (Male)"),
    ("190", "Ignare (Male)"),
    ("138", "Igor Teaforay (Female)"),
    ("118", "Inga Parsons (Female)"),
    ("281", "ink tree (Female)"),
    ("693", "inkwelldragon (Female)"),
    ("817", "iremonger (Female)"),
    ("229", "Iridescat (Female)"),
    ("788", "iscatel (Male)"),
    ("169", "Isosceles (Female)"),
    ("583", "J A Carter (Male)"),
    ("749", "J. A. Cook (Male)"),
    ("129", "J. M. Smallheer (Female)"),
    ("450", "J. Rebecca Franklin (Female)"),
    ("792", "J.C. (Male)"),
    ("209", "jabc1950 (Male)"),
    ("736", "Jack Farrell (Male)"),
    ("130", "Jacki Horn (Female)"),
    ("558", "Jackie Drown (Female)"),
    ("398", "Jacob Miller (Male)"),
    ("706", "Jacob Paine (Male)"),
    ("662", "Jacob Paul Starr (Male)"),
    ("151", "Jake Woldstad (Male)"),
    ("511", "James Christopher (Male)"),
    ("106", "James E. Carson (Male)"),
    ("204", "James K. White (Male)"),
    ("552", "James Smith (Male)"),
    ("892", "James Tiley (Male)"),
    ("406", "Jamey Osborne (Male)"),
    ("551", "Jan Baxter (Female)"),
    ("581", "Jan Dawn Doronila (Female)"),
    ("66", "Jan MacGillivray (Female)"),
    ("47", "Jane Greensmith (Female)"),
    ("585", "Janet (Female)"),
    ("466", "Janet Friday (Female)"),
    ("336", "Janet248 (Female)"),
    ("859", "Jared Hess (Male)"),
    ("380", "Jason Ingolfsland (Male)"),
    ("528", "Jason Mayoff (Male)"),
    ("889", "Jason Procopio (Male)"),
    ("709", "Jason X. (Male)"),
    ("410", "jburby (Male)"),
    ("776", "JDavidMoore (Male)"),
    ("46", "Jean O'Sullivan (Female)"),
    ("731", "Jeanette Ferguson (Female)"),
    ("292", "Jeanni Hall (Female)"),
    ("705", "Jeannie (Female)"),
    ("421", "Jeannie Tirado (Female)"),
    ("284", "Jeff K. (Male)"),
    ("51", "Jeff Robinson (Male)"),
    ("838", "Jeff Stuckey (Male)"),
    ("173", "jeffwiltzius (Male)"),
    ("100", "Jen Kidd (Female)"),
    ("759", "Jenna Lanman (Female)"),
    ("252", "Jennette Selig (Female)"),
    ("280", "Jennifer Crispin (Female)"),
    ("283", "Jennifer Lott (Female)"),
    ("688", "Jeremy Robertson (Male)"),
    ("492", "Jerome Lawsen (Male)"),
    ("559", "Jerry Romero (Male)"),
    ("296", "Jesse Crisp-Sears (Male)"),
    ("1", "Jessica Atha (Female)"),
    ("768", "Jewel Raquel (Female)"),
    ("434", "Jill (Female)"),
    ("31", "Jim Allman (Male)"),
    ("121", "Jim Eastman (Male)"),
    ("404", "Jim Mullins (Male)"),
    ("486", "Jim Ruddy (Male)"),
    ("346", "JimD (Male)"),
    ("223", "JimmyLogan (Male)"),
    ("461", "Jing Li (Female)"),
    ("813", "JLaddJr (Male)"),
    ("383", "Jo Karabasz (Female)"),
    ("874", "Joan Freeman (Female)"),
    ("294", "Joanne Pauwels (Female)"),
    ("651", "Joanne Rochon (Female)"),
    ("732", "Jodi Krangle (Female)"),
    ("829", "Joe Konno (Male)"),
    ("269", "Joe Mabry (Male)"),
    ("632", "JoeD (Male)"),
    ("613", "Joel Poortenga (Male)"),
    ("441", "John Lieder (Male)"),
    ("490", "John Nicholson (Male)"),
    ("641", "John Pruden (Male)"),
    ("602", "John Schuurman (Male)"),
    ("110", "JohnNewman (Male)"),
    ("699", "Jolie O'Dell (Female)"),
    ("261", "Jon Kerfoot (Male)"),
    ("400", "Jon Miller (Male)"),
    ("811", "Jon Sindell (Male)"),
    ("506", "Jonah Cummings (Male)"),
    ("677", "Jonathan Lange (Male)"),
    ("522", "Jordan (Male)"),
    ("498", "Joseph Finkberg (Male)"),
    ("472", "Joseph Lawler (Male)"),
    ("627", "Joseph Ugoretz (Male)"),
    ("533", "Josh Smith (Male)"),
    ("578", "Joshua B. Christensen (Male)"),
    ("497", "Joshua Paul Johnson (Male)"),
    ("381", "Joy Easton (Female)"),
    ("422", "Joy S Grape (Female)"),
    ("897", "Joyce Nussbaum (Female)"),
    ("146", "Juan Federico (Male)"),
    ("456", "Jud Niven (Male)"),
    ("671", "jude kaider (Male)"),
    ("325", "Jude Somers (Female)"),
    ("837", "Judith Brown (Female)"),
    ("748", "Judith Parker (Female)"),
    ("60", "Judy Bieber (Female)"),
    ("340", "Julia Kelley (Female)"),
    ("784", "Julian Jamison (Male)"),
    ("12", "Juliana M. (Female)"),
    ("111", "Julie Bynum (Female)"),
    ("676", "Julie K. Rose (Female)"),
    ("798", "Julie Levi (Female)"),
    ("206", "Julie Pandya (Female)"),
    ("392", "Justin S Barrett (Male)"),
    ("603", "K Hindall (Female)"),
    ("171", "Kalynda (Female)"),
    ("225", "Kancamagus (Male)"),
    ("193", "Karen (Female)"),
    ("70", "Karen Howard (Female)"),
    ("376", "Kate Sterner (Female)"),
    ("733", "Katherine (Female)"),
    ("457", "Kathleen Nelson (Female)"),
    ("887", "Kathrin Salazar (Female)"),
    ("644", "Kathryn Louise (Female)"),
    ("73", "Kathy (Female)"),
    ("553", "Kathy Jacobs (Female)"),
    ("619", "Katie Baynes (Female)"),
    ("714", "Katie Gibboney (Female)"),
    ("87", "Katie McClain (Female)"),
    ("210", "Katie Riley (Female)"),
    ("515", "Katine (Female)"),
    ("107", "Katryn Wiese (Female)"),
    ("302", "kattekliek (Female)"),
    ("567", "katyleah (Female)"),
    ("446", "kayo (Female)"),
    ("351", "Kehinde (Female)"),
    ("775", "Kele (Female)"),
    ("228", "kelleywyskiel (Female)"),
    ("764", "Kelli Robinson (Female)"),
    ("782", "Kelly Dougherty (Male)"),
    ("82", "Ken Crooker (Male)"),
    ("895", "Ken Sterry (Male)"),
    ("600", "KentF (Male)"),
    ("134", "Kevin Alix (Male)"),
    ("808", "Kevin Devine (Male)"),
    ("743", "Kevin Kivikko (Male)"),
    ("616", "Kevin LaVergne (Male)"),
    ("724", "Kevin Maxson (Male)"),
    ("105", "Kevin McAsh (Male)"),
    ("88", "Kevin Readdean (Male)"),
    ("493", "KHand (Female)"),
    ("120", "Kiki Baessell (Female)"),
    ("661", "Kim (Female)"),
    ("611", "Kim Braun (Female)"),
    ("234", "Kim S (Female)"),
    ("822", "Kim Stich (Male)"),
    ("471", "kindfish (Female)"),
    ("319", "kindlibrarian (Female)"),
    ("181", "Kirk Thomas (Male)"),
    ("142", "Kirsten Ferreri (Female)"),
    ("39", "Kirsten Nelson (Female)"),
    ("579", "kittyandcheese (Female)"),
    ("76", "Kristel Tretter (Female)"),
    ("849", "kristiface (Female)"),
    ("26", "Kristin Hughes (Female)"),
    ("307", "Kristin LeMoine (Female)"),
    ("388", "Krzysztof Rowinski (Male)"),
    ("509", "Kurt Copeland (Male)"),
    ("272", "Kurt Wong (Male)"),
    ("7", "Kyle M. (Male)"),
    ("184", "L D Hamilton (Female)"),
    ("104", "Larry Beasley (Male)"),
    ("154", "Laura Atkinson (Female)"),
    ("593", "Laura Koskinen (Female)"),
    ("241", "Lauren Jane (Female)"),
    ("458", "Laurie Anne Walden (Female)"),
    ("667", "Laurie Campbell (Female)"),
    ("314", "Leda (Female)"),
    ("580", "Lee Ann Howlett (Female)"),
    ("405", "Lee Smalley (Male)"),
    ("791", "Leon Mire (Male)"),
    ("301", "leonardswench (Female)"),
    ("195", "Leslie Stevens Suhy (Female)"),
    ("460", "Leslie Walden (Male)"),
    ("638", "lewildesen (Female)"),
    ("865", "librarianite (Female)"),
    ("315", "Lily Took (Female)"),
    ("258", "Linda Andrus (Female)"),
    ("188", "Linda Ciano (Female)"),
    ("562", "Linda Dougherty (Female)"),
    ("612", "Linda Hogan (Female)"),
    ("238", "Linda Lee Paquet (Female)"),
    ("144", "Linda Velwest (Female)"),
    ("384", "Lisa Chau (Female)"),
    ("469", "Lisa Phelps Gonzalez (Female)"),
    ("157", "Lita Ledesma (Female)"),
    ("610", "LivelyHive (Male)"),
    ("274", "LizMourant (Female)"),
    ("447", "Lizzie Oldfather (Female)"),
    ("655", "Logan McCamon (Male)"),
    ("358", "Logan West (Male)"),
    ("647", "Lois Browne (Female)"),
    ("235", "Lois C. Johnson (Female)"),
    ("205", "Lois Hill (Female)"),
    ("170", "Lori Arsenault (Female)"),
    ("214", "Lori Fuller Chugiak, AK (Female)"),
    ("832", "Lori Hebel (Female)"),
    ("143", "Lucretia B. (Female)"),
    ("10", "Lucy Perry (Female)"),
    ("496", "lukeprog (Male)"),
    ("871", "LuvDemBrooders (Female)"),
    ("194", "Lynne Handler (Female)"),
    ("331", "Lynne Ray (Female)"),
    ("230", "M. Craun (Male)"),
    ("563", "M.White (Male)"),
    ("707", "Maddie (Female)"),
    ("56", "Maire Rhode (Female)"),
    ("428", "Malcolm Cameron (Male)"),
    ("485", "Manjit Bains (Female)"),
    ("888", "Marco (Male)"),
    ("554", "Marcy Fraser (Female)"),
    ("719", "marevalo (Female)"),
    ("379", "Margaret Espaillat (Female)"),
    ("103", "Marian Brown (Female)"),
    ("323", "Marian Cervassi (Female)"),
    ("652", "Marianna Foos (Female)"),
    ("449", "MarianneVictoria (Female)"),
    ("658", "Marie Daum (Female)"),
    ("122", "Marie Hoffman (Female)"),
    ("516", "Marilyn Mack (Female)"),
    ("83", "Marion (Female)"),
    ("97", "Mark Bradford (Male)"),
    ("572", "Mark Cawley (Male)"),
    ("386", "Mark DeVol (Male)"),
    ("546", "Mark F. Smith (Male)"),
    ("437", "Mark Johnston (Male)"),
    ("27", "Mark Mickelson (Male)"),
    ("689", "Mark Penfold (Male)"),
    ("618", "Mark Wilson (Male)"),
    ("297", "Martin Reyto (Male)"),
    ("72", "Marty (Male)"),
    ("418", "martyd (Male)"),
    ("249", "Mary aka Breadchick (Female)"),
    ("251", "Mary Anderson (Female)"),
    ("510", "Mary Herndon Bell (Female)"),
    ("108", "Maryanka (Female)"),
    ("467", "MaryAnn (Female)"),
    ("463", "Matt Lusher (Male)"),
    ("825", "Matt Parker (Male)"),
    ("96", "Matt Warzel (Female)"),
    ("629", "Matt Wills (Male)"),
    ("168", "Matthew C. Heckel (Male)"),
    ("549", "Matthew Hinman (Male)"),
    ("124", "Matthew Reece (Male)"),
    ("291", "Matthew Shepherd (Male)"),
    ("797", "mawrtea (Male)"),
    ("276", "mbousquet (Female)"),
    ("382", "Meg Cowan (Female)"),
    ("373", "Megan-Jane Daniels Suyasu (Female)"),
    ("310", "Melanie Schleeter McCalmont (Female)"),
    ("65", "Melissa Burns-Price (Female)"),
    ("348", "Melora (Female)"),
    ("355", "Meredith Hughes (Female)"),
    ("636", "MGreenberg (Male)"),
    ("596", "Micah Sheppard (Male)"),
    ("423", "Michael Bradford (Male)"),
    ("158", "Michael Crowl (Male)"),
    ("824", "Michael Kirkpatrick (Male)"),
    ("176", "Michael Lipschultz (Male)"),
    ("401", "Michael Loftus (Male)"),
    ("700", "Michael Macedonia (Male)"),
    ("725", "Michael Monhollon (Male)"),
    ("500", "Michael Scherer (Male)"),
    ("145", "Michael Thomas Robinson (Male)"),
    ("680", "Michael Yard (Male)"),
    ("639", "Michelle Crandall (Female)"),
    ("356", "Michelle Day (Female)"),
    ("487", "Michelle Remington (Female)"),
    ("820", "MichelleHarris (Female)"),
    ("318", "Mike Bloomfield (Male)"),
    ("772", "Mike Conrad (Male)"),
    ("568", "Mike Kauffmann (Male)"),
    ("48", "Mike Okonek (Male)"),
    ("569", "Mike Rosenlof (Male)"),
    ("863", "Mike Schwabe (Male)"),
    ("544", "Mike Wajda (Male)"),
    ("42", "mikenkat (Male)"),
    ("507", "Mimi Wang (Female)"),
    ("180", "Miranda Stinson (Female)"),
    ("172", "Miriam Esther Goldman (Female)"),
    ("754", "Missie (Female)"),
    ("175", "Mitchell Dwyer (Male)"),
    ("512", "MitchHerd (Male)"),
    ("780", "MixieArmadillo (Female)"),
    ("741", "moe (Female)"),
    ("268", "Moira Fogarty (Female)"),
    ("262", "Monica Knuppe (Female)"),
    ("345", "Monique (Female)"),
    ("750", "Morey Kunin (Male)"),
    ("21", "Morgan Saletta (Male)"),
    ("68", "Morgan Schlicker (Female)"),
    ("186", "morganreads (Male)"),
    ("295", "Mr Krause (Male)"),
    ("275", "Mr. Baby Man (Male)"),
    ("370", "msjodi777 (Female)"),
    ("133", "MsMO (Female)"),
    ("560", "Mudlark (Female)"),
    ("322", "Mur Lafferty (Female)"),
    ("443", "Muriel (Female)"),
    ("635", "mwalimu (Female)"),
    ("49", "n8evv (Male)"),
    ("112", "Nancy Roberts (Female)"),
    ("94", "Natalie (Female)"),
    ("13", "Natalie Sullivan (Female)"),
    ("287", "Ned Troxel (Male)"),
    ("894", "Nichelle von Lauder (Female)"),
    ("855", "Nicholas Feulner (Male)"),
    ("364", "NickNumber (Male)"),
    ("313", "Nicole Kay (Female)"),
    ("174", "nlonghu (Male)"),
    ("271", "NoelBadrian (Male)"),
    ("402", "nomorejeffs (Male)"),
    ("648", "Notelrac (Male)"),
    ("622", "ontheroad (Male)"),
    ("62", "P Moscato (Female)"),
    ("503", "P. J. Morgan (Female)"),
    ("556", "Paige G (Female)"),
    ("165", "paintgirl (Female)"),
    ("424", "Pamela Krantz (Female)"),
    ("41", "Pamnache (Female)"),
    ("298", "Pat Elder (Female)"),
    ("80", "Pat Redstone (Female)"),
    ("316", "Patricia Oakley (Female)"),
    ("20", "Patricia Rutledge (Female)"),
    ("89", "Patrick Painter (Male)"),
    ("518", "Patrick Reinhart (Male)"),
    ("74", "Patti Cunningham (Female)"),
    ("621", "pattymarie (Female)"),
    ("414", "Paul Adamson (Male)"),
    ("84", "Paul Harvey (Male)"),
    ("866", "Paul Henry Tremblay (Male)"),
    ("92", "Paul Siegel (Male)"),
    ("576", "Paula Berinstein (Female)"),
    ("363", "paulino (Male)"),
    ("339", "PDyer (Male)"),
    ("753", "pekein (Male)"),
    ("164", "PennyAnn (Female)"),
    ("501", "Pete Williams, Pittsburgh, PA (Male)"),
    ("67", "Phil Chenevert (Male)"),
    ("722", "Phil Surette (Male)"),
    ("657", "PopularOutcast (Female)"),
    ("826", "Preston McConkie (Male)"),
    ("529", "PrincessG (Female)"),
    ("860", "priscilla hewitt (Female)"),
    ("429", "Professor Chronotis (Male)"),
    ("337", "progressingamerica (Male)"),
    ("665", "Psuke Bariah (Female)"),
    ("332", "pww214 (Male)"),
    ("468", "Qhali (Female)"),
    ("508", "Quentin (Male)"),
    ("189", "Quentin Manuel (Male)"),
    ("843", "R. Francis Smith (Male)"),
    ("718", "R.W. Rushing (Male)"),
    ("723", "Rachel Gatwood (Female)"),
    ("664", "Rachel P. (Female)"),
    ("396", "Rachel Weaver (Female)"),
    ("141", "Rachell Lovett (Female)"),
    ("828", "radioreader (Male)"),
    ("482", "Ralph Volpi (Male)"),
    ("624", "Randi Warwick (Female)"),
    ("588", "Rapunzelina (Female)"),
    ("342", "rasputin (Male)"),
    ("818", "Ray Clare (Male)"),
    ("226", "Rayne (Male)"),
    ("385", "rdmagpie (Male)"),
    ("505", "ReadWriteLib (Female)"),
    ("61", "Rebecca King (Female)"),
    ("260", "Rebecca Owens (Female)"),
    ("691", "Rechelle (Female)"),
    ("415", "RedToby (Male)"),
    ("548", "Reeses118 (Female)"),
    ("524", "Rhonda Federman (Female)"),
    ("335", "Richard Carpenter (Male)"),
    ("119", "Richard Ellwood (Male)"),
    ("571", "Richard Jackson (Male)"),
    ("43", "Rick Cahill (Male)"),
    ("830", "Riddleman (Female)"),
    ("793", "RK Wilcox (Male)"),
    ("317", "Rob James (Male)"),
    ("847", "Rob Smith (Male)"),
    ("247", "RobbieRogers (Female)"),
    ("660", "Robert Beach (Male)"),
    ("604", "Robert Fletcher (Male)"),
    ("867", "Robert Foster (Male)"),
    ("730", "Robert Garrison (Male)"),
    ("36", "Robert Harder (Male)"),
    ("221", "Robert Hoffman (Male)"),
    ("413", "Robert Scott (Male)"),
    ("30", "Robin Cotter (Female)"),
    ("116", "Roger Melin (Male)"),
    ("879", "Roger Turnau (Male)"),
    ("299", "Rohanna (Female)"),
    ("575", "Rom Maczka (Male)"),
    ("675", "RoseA (Female)"),
    ("115", "Roseanne Schmidt (Female)"),
    ("90", "Ross Williamson (Male)"),
    ("433", "Roxanna Nazari (Female)"),
    ("767", "Roy Schreiber (Male)"),
    ("369", "Russ Lemker (Male)"),
    ("876", "Russ Maxwell (Male)"),
    ("615", "Ryan (Male)"),
    ("338", "Ryan Gubele (Male)"),
    ("350", "Ryan Ransom (Male)"),
    ("787", "ryanaw (Male)"),
    ("212", "Sam Naishtat (Male)"),
    ("409", "Samanem (Male)"),
    ("265", "Samantha J Gubitz (Female)"),
    ("207", "Samantha Miles (Female)"),
    ("625", "Sandie Guenther (Female)"),
    ("290", "Sarah Bean (Female)"),
    ("245", "Sarah Crampton (Female)"),
    ("279", "Sarah Jennings (Female)"),
    ("545", "Sarah K (Female)"),
    ("455", "Sarah Key-DeLyria (Female)"),
    ("494", "Sarah Nuxoll (Female)"),
    ("819", "SarahHadley (Female)"),
    ("162", "Sarika Pawar (Female)"),
    ("352", "sbburke (Female)"),
    ("900", "Scoot (Male)"),
    ("738", "Scott D. Farquhar (Male)"),
    ("696", "Scott Henkel (Male)"),
    ("729", "Scott Mather (Male)"),
    ("278", "Scott Merrill (Male)"),
    ("102", "Scott Sherris (Male)"),
    ("246", "Scott Snowman (Male)"),
    ("427", "ScottReyonoldsVoice (Male)"),
    ("353", "Scotty (Male)"),
    ("360", "scoutman77 (Male)"),
    ("668", "sdaeley17 (Male)"),
    ("240", "Sean McGaughey (Male)"),
    ("137", "Sean Michael Hogan (Male)"),
    ("877", "sebrazer (Female)"),
    ("727", "selniff (Female)"),
    ("746", "serenitylee (Female)"),
    ("687", "Seyed (Male)"),
    ("875", "shalclark (Female)"),
    ("59", "Shana Cohen (Female)"),
    ("273", "Sharon Kilmer (Female)"),
    ("444", "Sharon Riskedahl (Female)"),
    ("38", "Shauna Kennett (Female)"),
    ("417", "Shawn Craig Smith (Male)"),
    ("845", "Shirley Ellen (Female)"),
    ("33", "Shirleyroses (Female)"),
    ("833", "Shubda (Female)"),
    ("690", "Shurtagal (Male)"),
    ("254", "Sibella Denton (Female)"),
    ("704", "SilverG (Male)"),
    ("521", "Simon Dexter (Male)"),
    ("530", "Simon-Peter Zak (Male)"),
    ("475", "Sirmelja (Female)"),
    ("367", "smhamon (Male)"),
    ("659", "Son of the Exiles (Male)"),
    ("595", "Sonserae Leese-Calver (Female)"),
    ("525", "SopranoHarmony (Female)"),
    ("99", "southernemma (Female)"),
    ("816", "spiderman0521 (Male)"),
    ("488", "srshel (Female)"),
    ("539", "Stefanie Heinrichs (Female)"),
    ("903", "Stephanie Dupal-Demartin (Female)"),
    ("439", "Stephanie Konig (Female)"),
    ("282", "Stephanie Land (Female)"),
    ("166", "Stephanie Lee (Female)"),
    ("765", "stepheather (Female)"),
    ("836", "Stephen Escalera (Male)"),
    ("489", "Stephen L. Moss (Male)"),
    ("198", "Steve Jackson (Male)"),
    ("5", "Steven H. Wilson (Male)"),
    ("416", "Steven Reynolds (Male)"),
    ("674", "Steven Rushing (Male)"),
    ("362", "Steven Seitel (Male)"),
    ("755", "stmacduff (Female)"),
    ("64", "Sue Anderson (Female)"),
    ("601", "Suebee (Female)"),
    ("535", "Sunni West (Female)"),
    ("153", "Susan Denney (Female)"),
    ("711", "Susan Hanfield (Female)"),
    ("840", "susanfrom (Female)"),
    ("566", "swade (Female)"),
    ("321", "Symmie (Female)"),
    ("878", "T Michael Burke (Male)"),
    ("769", "Tad E. (Male)"),
    ("851", "taijohn (Male)"),
    ("372", "Taliesin (Female)"),
    ("695", "Tammy Porter (Female)"),
    ("420", "Tammy Stalcup (Female)"),
    ("365", "tamurile (Female)"),
    ("762", "TBOL3 (Male)"),
    ("799", "Ted Delorme (Male)"),
    ("266", "Terra Mendoza (Female)"),
    ("630", "Terry Goodyer (Female)"),
    ("669", "Terry Torres (Male)"),
    ("801", "texttalker (Male)"),
    ("29", "Theresa L. Downey (Female)"),
    ("329", "thomahal (Male)"),
    ("763", "Thomas Davoren (Male)"),
    ("218", "Tiffany J. Kim (Female)"),
    ("53", "Tim Cote (Male)"),
    ("484", "Tim Ferreira (Male)"),
    ("474", "Tim Lundeen (Male)"),
    ("187", "Timothy Lucas (Male)"),
    ("222", "Timothy Luke (Male)"),
    ("28", "Timothy Pinkham (Male)"),
    ("288", "timothyFR (Male)"),
    ("430", "Tina Nuzzi (Female)"),
    ("853", "Tina Tilney (Female)"),
    ("592", "tittletattle (Female)"),
    ("868", "TJDasch (Male)"),
    ("495", "Todd Cranston-Cuebas (Male)"),
    ("438", "Todd Lennon (Male)"),
    ("303", "Tom Geller (Male)"),
    ("136", "Tom Lennon (Male)"),
    ("395", "Tom Watts (Male)"),
    ("646", "Tom Yates (Male)"),
    ("520", "Tony Hightower (Male)"),
    ("233", "Tony Maxey (Male)"),
    ("606", "Tony Russell (Male)"),
    ("634", "tonypettit (Male)"),
    ("643", "Topaz (Male)"),
    ("862", "Tracy Datlen (Female)"),
    ("179", "TriciaG (Female)"),
    ("208", "Tyran Rexx (Male)"),
    ("547", "TyroneS (Male)"),
    ("480", "Tysto (Male)"),
    ("270", "Utek (Male)"),
    ("650", "Val Grimm (Female)"),
    ("239", "Veronica Jenkins (Female)"),
    ("623", "Victoria Slonosky (Female)"),
    ("587", "vikvenom (Female)"),
    ("152", "Vin Reilly (Male)"),
    ("52", "Vincent Tapia (Female)"),
    ("885", "Vinnie Tesla (Male)"),
    ("24", "Vinny Bove (Male)"),
    ("18", "Vivian Bush (Female)"),
    ("590", "voicebynatalie (Male)"),
    ("526", "von (Male)"),
    ("891", "Wasichu (Male)"),
    ("681", "Wayfarer (Female)"),
    ("359", "wedschild (Female)"),
    ("462", "Wendy Almeida (Female)"),
    ("532", "Wendy G. (Female)"),
    ("678", "Wesseling (Male)"),
    ("127", "WestWestest (Female)"),
    ("125", "Westwinds12 (Female)"),
    ("841", "wildalaska (Male)"),
    ("726", "Wiley Combs (Male)"),
    ("308", "Will Larson (Male)"),
    ("394", "William Kevin Manire (Male)"),
    ("778", "wrongshore (Male)"),
    ("703", "wvthcomp (Male)"),
    ("131", "Yazpistachio (Female)"),
    ("177", "Yvonne Smith (Female)"),
    ("823", "Zale Schafer (Rose May Chamberlin Memorial Foundat (Female)"),
    ("617", "zcameo (Female)"),
    ("781", "Zloot (Male)"),
]
