# -*- coding: utf-8 -*-
from odoo import _, fields, models
from odoo.exceptions import UserError

from .deployment_agent_client import DeploymentAgentClient


class DeploymentServer(models.Model):
    """One Odoo-hosting server this business can deploy customer
    instances onto: the single shared multi-tenant box (one record,
    kind='shared', set up once by hand - this module never bootstraps
    it), or one dedicated record per customer needing their own VPS.
    """
    _name = 'deployment.server'
    _description = 'Odoo Deployment Server'
    _inherit = ['mail.thread']
    _rec_name = 'name'

    name = fields.Char(required=True)
    hostname = fields.Char(
        required=True,
        help="This server's own admin hostname or IP - not a "
             "customer's domain (a shared server hosts many).")
    kind = fields.Selection(
        [('shared', 'Shared Multi-Tenant'), ('dedicated', 'Dedicated')],
        required=True, default='dedicated')
    partner_id = fields.Many2one(
        'res.partner',
        help="For a dedicated server, the customer it belongs to. "
             "Left empty for the shared server.")
    agent_url = fields.Char(
        required=True,
        help="Base URL of this server's own deploy agent, "
             "e.g. https://vps1.example.com:8765")
    agent_token = fields.Char(
        help="Bearer token for the agent - generated by "
             "scripts/bootstrap.sh (see meskis-deploy-agent) and "
             "pasted in here by hand, never entered by a customer.")
    bootstrap_state = fields.Selection(
        [('not_needed', 'Not Needed (Shared Server)'),
         ('pending', 'Pending'),
         ('done', 'Done')],
        default='pending', required=True, tracking=True)
    last_health_check = fields.Datetime(readonly=True)
    last_health_ok = fields.Boolean(readonly=True)

    def _get_client(self):
        self.ensure_one()
        if not self.agent_token:
            raise UserError(_(
                "%(server)s has no agent token yet - run the bootstrap "
                "script and paste the token it prints back in here first.",
                server=self.name))
        return DeploymentAgentClient(self.agent_url, self.agent_token)

    def action_test_connection(self):
        """Deliberately never raises, on either outcome - a health
        check failing is an expected, not exceptional, thing to
        discover here, and Odoo's own request-transaction handling
        rolls back ANY write made earlier in the same call once an
        exception actually escapes it (confirmed the hard way: the
        obvious "write the result, then raise a UserError as the
        success notice" pattern - the one signalwire.server's own
        action_test_connection uses - silently discarded the write in
        both directions, since raising unwinds the whole transaction,
        not just the notice). A display_notification client action
        shows the same message without ever raising, so the write
        actually survives either way.
        """
        self.ensure_one()
        client = self._get_client()
        try:
            result = client.health()
        except Exception as exc:
            self.write({'last_health_check': fields.Datetime.now(), 'last_health_ok': False})
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _("Connection failed"),
                    'message': str(exc),
                    'type': 'danger',
                },
            }
        self.write({'last_health_check': fields.Datetime.now(), 'last_health_ok': True})
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _("Connected"),
                'message': _(
                    "Agent version: %(version)s.", version=result.get('version', '?')),
                'type': 'success',
            },
        }
