# -*- coding: utf-8 -*-
"""Thin HTTP client for a meskis-deploy-agent instance (see the
separate meskis-deploy-agent repo). Isolated in its own module, same
reasoning as HestiaCPClient/SignalWireClient elsewhere in this repo -
one small wire-format surface, kept correct in one place for both
tests (mock this class directly) and the model code that uses it.
"""
import logging

import requests

from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)

HEALTH_TIMEOUT = 10
# Creating a database (odoo-bin -i <modules> --stop-after-init) can
# genuinely take minutes for a suite with several modules - a short
# timeout here would abort a request that's actually still working.
ACTION_TIMEOUT = 600


class DeploymentAgentError(UserError):
    """Raised when a meskis-deploy-agent instance is unreachable or
    returns an error.
    """


class DeploymentAgentClient:
    """:param base_url: e.g. "https://vps1.example.com:8765" (or
        wherever the agent's reverse-proxied path actually is)
    :param token: the agent's own bearer token, generated by
        scripts/bootstrap.sh and pasted into deployment.server by hand.
    """

    def __init__(self, base_url, token):
        self.base_url = base_url.rstrip('/')
        self.token = token

    def _post(self, path, payload):
        url = f'{self.base_url}{path}'
        try:
            response = requests.post(
                url, json=payload, timeout=ACTION_TIMEOUT,
                headers={'Authorization': f'Bearer {self.token}'})
        except requests.RequestException as exc:
            _logger.warning('Deploy agent request failed (%s): %s', path, exc)
            raise DeploymentAgentError(
                f'Could not reach the deploy agent at {self.base_url}: {exc}') from exc

        if response.status_code >= 400:
            detail = response.text
            try:
                detail = response.json().get('detail', detail)
            except ValueError:
                pass
            raise DeploymentAgentError(
                f'Deploy agent request to {path} failed '
                f'(HTTP {response.status_code}): {detail}')
        return response.json() if response.content else {}

    def health(self):
        try:
            response = requests.get(f'{self.base_url}/health', timeout=HEALTH_TIMEOUT)
        except requests.RequestException as exc:
            raise DeploymentAgentError(
                f'Could not reach the deploy agent at {self.base_url}: {exc}') from exc
        if response.status_code != 200:
            raise DeploymentAgentError(
                f'Deploy agent health check failed (HTTP {response.status_code})')
        return response.json()

    def create_vhost(self, domain, db_name):
        return self._post('/vhosts', {'domain': domain, 'db_name': db_name})

    def issue_certificate(self, domain):
        return self._post('/certificates', {'domain': domain})

    def create_database(self, db_name, modules, admin_email, company_name):
        return self._post('/databases', {
            'db_name': db_name, 'modules': modules,
            'admin_email': admin_email, 'company_name': company_name,
        })
