# -*- coding: utf-8 -*-
import re

from odoo import _, fields, models
from odoo.exceptions import UserError

from .deployment_agent_client import DeploymentAgentClient


class DeploymentServer(models.Model):
    """One Odoo-hosting server this business can deploy customer
    instances onto: the single shared multi-tenant box (one record,
    kind='shared', set up once by hand - this module never bootstraps
    it), or one dedicated record per customer needing their own VPS.
    """
    _name = 'deployment.server'
    _description = 'Odoo Deployment Server'
    _inherit = ['mail.thread']
    _rec_name = 'name'

    name = fields.Char(required=True)
    hostname = fields.Char(
        help="This server's own admin hostname or IP - not a "
             "customer's domain (a shared server hosts many). Not "
             "required at creation time for an UpCloud-provisioned "
             "server - Create UpCloud Server fills it in with the "
             "real public IP once the VPS actually exists.")
    kind = fields.Selection(
        [('shared', 'Shared Multi-Tenant'), ('dedicated', 'Dedicated')],
        required=True, default='dedicated')
    partner_id = fields.Many2one(
        'res.partner',
        help="For a dedicated server, the customer it belongs to. "
             "Left empty for the shared server.")
    agent_url = fields.Char(
        help="Base URL of this server's own deploy agent, "
             "e.g. https://vps1.example.com:8765 - not required at "
             "creation time (an UpCloud-provisioned server doesn't "
             "even have a hostname yet until Create UpCloud Server "
             "runs), only once actually calling the agent.")
    agent_token = fields.Char(
        help="Bearer token for the agent - generated by "
             "scripts/bootstrap.sh (see meskis-deploy-agent) and "
             "pasted in here by hand, never entered by a customer.")
    bootstrap_state = fields.Selection(
        [('not_needed', 'Not Needed (Shared Server)'),
         ('pending', 'Pending'),
         ('done', 'Done')],
        default='pending', required=True, tracking=True)
    last_health_check = fields.Datetime(readonly=True)
    last_health_ok = fields.Boolean(readonly=True)

    # -- optional: automated VPS creation via UpCloud, for kind='dedicated' -
    vps_provider = fields.Selection(
        [('manual', 'Manual / Customer-Provided'), ('upcloud', 'UpCloud')],
        default='manual', required=True,
        help="'Manual' covers both a customer's own server and any "
             "VPS provider without an automated integration here - "
             "the bootstrap script still gets run by hand either way, "
             "this only automates the earlier \"does the box exist "
             "yet at all\" step.")
    upcloud_account_id = fields.Many2one('upcloud.account', string="UpCloud Account")
    upcloud_uuid = fields.Char(readonly=True, copy=False, help="Set once the VPS is created.")
    upcloud_state = fields.Char(
        readonly=True, copy=False,
        help="UpCloud's own state string for this server (maintenance/"
             "started/stopped/...) - refreshed by Check VPS Status, "
             "not live.")
    upcloud_zone = fields.Char(help="Defaults from the UpCloud account if left empty.")
    upcloud_plan = fields.Char(help="Defaults from the UpCloud account if left empty.")
    upcloud_template_uuid = fields.Char(
        help="Defaults from the UpCloud account if left empty.")

    def _get_client(self):
        self.ensure_one()
        if not self.agent_url:
            raise UserError(_(
                "%(server)s has no agent URL yet - it needs a real "
                "hostname/IP first (Create UpCloud Server sets this "
                "automatically; for a manual server, set it by hand).",
                server=self.name))
        if not self.agent_token:
            raise UserError(_(
                "%(server)s has no agent token yet - run the bootstrap "
                "script and paste the token it prints back in here first.",
                server=self.name))
        return DeploymentAgentClient(self.agent_url, self.agent_token)

    def action_test_connection(self):
        """Deliberately never raises, on either outcome - a health
        check failing is an expected, not exceptional, thing to
        discover here, and Odoo's own request-transaction handling
        rolls back ANY write made earlier in the same call once an
        exception actually escapes it (confirmed the hard way: the
        obvious "write the result, then raise a UserError as the
        success notice" pattern - the one signalwire.server's own
        action_test_connection uses - silently discarded the write in
        both directions, since raising unwinds the whole transaction,
        not just the notice). A display_notification client action
        shows the same message without ever raising, so the write
        actually survives either way.
        """
        self.ensure_one()
        client = self._get_client()
        try:
            result = client.health()
        except Exception as exc:
            self.write({'last_health_check': fields.Datetime.now(), 'last_health_ok': False})
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _("Connection failed"),
                    'message': str(exc),
                    'type': 'danger',
                },
            }
        self.write({'last_health_check': fields.Datetime.now(), 'last_health_ok': True})
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _("Connected"),
                'message': _(
                    "Agent version: %(version)s.", version=result.get('version', '?')),
                'type': 'success',
            },
        }

    # -- UpCloud VPS creation ------------------------------------------------

    def _upcloud_provisional_hostname(self):
        """A safe, valid-looking hostname to hand UpCloud for a server
        whose own hostname field hasn't been set yet - only used as
        the VM's internal label; deployment.server's own hostname
        field gets overwritten with the real public IP right after.
        """
        self.ensure_one()
        slug = re.sub(r'[^a-z0-9-]+', '-', (self.name or 'server').lower()).strip('-') or 'server'
        return f'{slug}.upcloud.internal'

    def action_create_upcloud_server(self):
        """Creates the actual VPS (real money) and stores its UUID/IP
        - deliberately does NOT block waiting for it to finish booting
        (UpCloud's own create call returns state "maintenance", and
        confirmed live that "started" alone doesn't even mean SSH is
        up yet - can take upwards of a minute end to end). Click
        "Check VPS Status" afterward, once, before running the
        bootstrap script.
        """
        self.ensure_one()
        if self.vps_provider != 'upcloud':
            raise UserError(_("This server isn't configured for UpCloud provisioning."))
        if not self.upcloud_account_id:
            raise UserError(_("Choose an UpCloud Account first."))
        if self.upcloud_uuid:
            raise UserError(_("%(server)s already has an UpCloud VPS created.", server=self.name))

        account = self.upcloud_account_id
        client = account._get_client()
        server = client.create_server(
            zone=self.upcloud_zone or account.default_zone,
            plan=self.upcloud_plan or account.default_plan,
            template_uuid=self.upcloud_template_uuid or account.default_template_uuid,
            title=self.name,
            # This is UpCloud's own idea of the VM's hostname (a
            # sensible placeholder if not set yet) - overwritten below
            # with the real public IP the moment it comes back, so the
            # field goes on to mean "how to actually reach this
            # server" from here on, same as every other deployment.server.
            hostname=self.hostname or self._upcloud_provisional_hostname(),
            ssh_public_key=account.ssh_public_key,
        )
        public_ip = next(
            (ip['address'] for ip in server.get('ip_addresses', {}).get('ip_address', [])
             if ip.get('access') == 'public'), None)
        self.write({
            'upcloud_uuid': server['uuid'],
            'upcloud_state': server.get('state'),
            'hostname': public_ip or self.hostname,
        })
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _("VPS creation started"),
                'message': _(
                    "UUID %(uuid)s, IP %(ip)s - check status in a "
                    "minute or two before trying to SSH in.",
                    uuid=server['uuid'], ip=public_ip or '?'),
                'type': 'success',
            },
        }

    def action_check_upcloud_status(self):
        self.ensure_one()
        if not self.upcloud_uuid:
            raise UserError(_("%(server)s has no UpCloud VPS created yet.", server=self.name))
        server = self.upcloud_account_id._get_client().get_server(self.upcloud_uuid)
        self.upcloud_state = server.get('state')
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _("UpCloud status: %(state)s", state=self.upcloud_state),
                'message': _(
                    "SSH may take a little longer to come up even "
                    "after this shows \"started\"."
                ) if self.upcloud_state == 'started' else _(
                    "Still provisioning - check again shortly."),
                'type': 'success' if self.upcloud_state == 'started' else 'info',
            },
        }

    def action_destroy_upcloud_server(self):
        """One-way and real money - stops then deletes the VPS
        (including its storage). Used for tearing down an abandoned/
        cancelled deployment, not part of the normal happy path.
        """
        self.ensure_one()
        if not self.upcloud_uuid:
            raise UserError(_("%(server)s has no UpCloud VPS to destroy.", server=self.name))
        client = self.upcloud_account_id._get_client()
        client.stop_server(self.upcloud_uuid)
        # A delete right after stop isn't guaranteed to succeed - the
        # server needs to actually reach "stopped" first (confirmed
        # live, see UpCloudClient.wait_for_state's own docstring).
        client.wait_for_state(self.upcloud_uuid, 'stopped')
        client.delete_server(self.upcloud_uuid, delete_storages=True)
        self.write({'upcloud_uuid': False, 'upcloud_state': False})
